---
title: "Untitled"
author: "yuki"
date: "2022-12-04"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(bruceR)
```

```{r setup, include=FALSE}
setwd("C:/Users/hmz19/Desktop/YuKi_Project/Mental Health/Mental_Health_Chuan-Peng_Lab/5_Analysis/5_1_Depression/5_1_2_Jaccard Index/code")
raw <- read.csv("C:/Users/hmz19/Desktop/YuKi_Project/Mental Health/Mental_Health_Chuan-Peng_Lab/5_Analysis/5_1_Depression/5_1_2_Jaccard Index/data/table1.csv")

n_col <- ncol(raw)
n_row <- nrow(raw)
```

```{r setup, include=FALSE}
blank <- data.frame(matrix(NA, nrow = n_col, ncol = n_col))
rownames(blank) <- colnames(raw)
colnames(blank) <- colnames(raw)
```

```{r setup, include=FALSE}
blank_r <- data.frame(matrix(NA, nrow = n_col, ncol = n_col))
rownames(blank_r) <- colnames(raw)
colnames(blank_r) <- colnames(raw)
```

```{r setup, include=FALSE}
for (i in 1:n_col){
  for (j in 1:n_col) { s <- raw %>%
                              dplyr::select(.,i,j) %>% #选择第i列和j列
                              dplyr::mutate(sum = rowSums(., na.rm=TRUE)) %>% #新建一列sum，sum=所有列的和
                              dplyr::filter(.,sum == 2) %>% #选择出所有sum=2的行
                              dplyr::summarise(.,n()) #计算一共有多少行
                         count <- as.numeric(s$`n()`) #将行数变为数值赋值
                         blank[i,j] <- count #将数值放入事先做好的26*26矩阵中
                         
  }
}
```

```{r setup, include=FALSE}
for (i in 1:n_col){
  for (j in 1:n_col) { s <- raw %>%
                              dplyr::select(.,i,j) %>% #选择第i列和j列
                              dplyr::mutate(sum = rowSums(., na.rm=TRUE)) %>% #新建一列sum，sum=所有列的和
                              dplyr::filter(.,sum == 2) %>% #选择出所有sum=2的行
                              dplyr::summarise(.,n()) #计算一共有多少行
                      
                       u1 <- raw %>%
                         dplyr::select(.,i) %>% #选择第i列
                         dplyr::mutate(sum = rowSums(., na.rm=TRUE)) %>% #新建一列sum，sum=所有列的和
                         dplyr::filter(.,sum == 1) %>% #选择出所有sum=1的行
                         dplyr::summarise(.,n()) #计算一共有多少行

                       u2 <- raw %>%
                         dplyr::select(.,j) %>% #选择第j列
                         dplyr::mutate(sum = rowSums(., na.rm=TRUE)) %>% #新建一列sum，sum=所有列的和
                         dplyr::filter(.,sum == 1) %>% #选择出所有sum=1的行
                         dplyr::summarise(.,n()) #计算一共有多少行
                                              
                         count_s <- as.numeric(s$`n()`) #将行数变为数值赋值
                         count_u1 <- as.numeric(u1$`n()`) #将行数变为数值赋值
                         count_u2 <- as.numeric(u2$`n()`) #将行数变为数值赋值
                         
                         blank_r[i,j] <- count_s/(count_u1 + count_u2 - count_s) #将数值放入事先做好的26*26矩阵中
                         
  }
}
```

```{r setup, include=FALSE}
write.csv(blank, "C:/Users/hmz19/Desktop/YuKi_Project/Mental Health/Mental_Health_Chuan-Peng_Lab/5_Analysis/5_1_Depression/5_1_2_Jaccard Index/OUTPUT/Jaccard_Index.csv",row.names=TRUE)
write.csv(blank_r, "C:/Users/hmz19/Desktop/YuKi_Project/Mental Health/Mental_Health_Chuan-Peng_Lab/5_Analysis/5_1_Depression/5_1_2_Jaccard Index/OUTPUT/Jaccard_Index_ratio.csv",row.names=TRUE)
```