---
title: "Re_Heatmap"
author: "yuki"
date: "2023-10-27"
output: html_document
---
```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(reshape2)
library(patchwork)

library(corrplot)
library(RColorBrewer)
library(grDevices)

library(tinylabels)
library(papaja)
```

```{r}
df_ji <- read.csv("../DATA/Jaccard_Index_ratio.csv") %>%
  dplyr::select(-Scales) %>%
  base::as.matrix(.)
base::row.names(df_ji) <- c(
  "MSSMHS", "CSSDS",
  #
  "CDI", "DSRSC", "BDI-I", "DSI", "HAMD", 
  #
  "SDS", "SCL-90", "CES-D", 
  "BDI-II", "PHQ-9", "DASS-21", "CBCL_boy", "CBCL_girl", "MFQ-C", 
  "CES-D-C", "ADI", "BSRS", "CES-D-13", "CEPS", "HADS", 
  "Ji_2007", "KADS-11", "Sakuma_2010", "SMFQ", "UPI", "CCSMHS"
)
base::colnames(df_ji) <- c(
  "MSSMHS", "CSSDS",
  #
  "CDI", "DSRSC", "BDI-I", "DSI", "HAMD", 
  #
  "SDS", "SCL-90", "CES-D", 
  "BDI-II", "PHQ-9", "DASS-21", "CBCL_boy", "CBCL_girl", "MFQ-C", 
  "CES-D-C", "ADI", "BSRS", "CES-D-13", "CEPS", "HADS", 
  "Ji_2007", "KADS-11", "Sakuma_2010", "SMFQ", "UPI", "CCSMHS"
)
```

```{r}
grDevices::pdf(
  file = "../FIGURE/2_Heatmap.pdf", 
  width = 16, height = 12,
)
corrplot::corrplot(
  df_ji,
  method = "circle",
  addCoef.col = 'black',
  diag=FALSE,
  addrect = 2,
  type = "upper", # pper triangle
  order = "original", # variables order
  col.lim = c(0.00, 1.00), # limits
  is.corr = FALSE, # correlation or not
  col = c("#FFFAC1", "#FFE569", "#FFC633", "#FF8B0A", "#B70404")  # <-- 改为5级颜色
) %>%
  corrRect(name = c("MSSMHS", "CDI", "SDS", "CCSMHS"))
dev.off()
```
